{{- if .Values.admissionController.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vertical-pod-autoscaler.admissionController.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}