{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  labels:
    app: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
spec:
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
{{- end }}
