{{- if and .Values.admissionController.enabled .Values.admissionController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.serviceAccount.name" . }}
  {{- if .Values.admissionController.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.admissionController.serviceAccount.annotations | nindent 8 }}
  {{- end }}
{{- end }}
