{{- if and .Values.admissionController.enabled .Values.admissionController.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "vertical-pod-autoscaler.admissionController.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
    {{- with .Values.admissionController.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.admissionController.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.admissionController.metrics.service.port }}
      protocol: TCP
      targetPort: prometheus
  selector:
    {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 4 }}
{{- end -}}
