{{- if and .Values.admissionController.enabled .Values.admissionController.podMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
  {{- with .Values.admissionController.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.admissionController.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: prometheus
  {{- with .Values.admissionController.podMonitor.extraPodMetricsEndpoints }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
