apiVersion: v2
name: cluster-autoscaler-kwok
description: A minimalistic Helm chart for Cluster-Autoscaler's KwoK Provider, designed specifically for local and CI/CD E2E testing environments.
type: application
version: 0.0.0
appVersion: 0.0.0
