# Generated folders and files are supposed to be excluded from the
# list if pre-commit inconsistencies in generated content by modifying
# them.
exclude: |
  (?x)^(
    addon-resizer/vendor/ |
    cluster-autoscaler/cloudprovider/oci/vendor-internal/ |
    vertical-pod-autoscaler/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
    rev: v3.1.0
  - repo: https://github.com/gruntwork-io/pre-commit
    hooks:
      - id: helmlint
    rev: v0.1.9
  - repo: https://github.com/norwoodj/helm-docs
    hooks:
      - id: helm-docs-built
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
    rev: v1.14.2
  - repo: local
    hooks:
      - id : update-flags
        name: Update Cluster-Autoscaler Flags Table
        entry: bash cluster-autoscaler/hack/update-faq-flags.sh
        language: system
        files: cluster-autoscaler/config/flags/flags\.go
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt
        
