apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- toYaml .Values.commonLabels | nindent 6 }}
