apiVersion: v1alpha1
readNodesFrom: cluster # possible values: [cluster,configmap]
nodegroups:
  # to specify how to group nodes into a nodegroup
  # e.g., you want to treat nodes with same instance type as a nodegroup
  # node1: m5.xlarge
  # node2: c5.xlarge
  # node3: m5.xlarge
  # nodegroup1: [node1,node3]
  # nodegroup2: [node2]
  fromNodeLabelKey: "node.kubernetes.io/instance-type"
  # you can either specify fromNodeLabelKey OR fromNodeAnnotationKey
  # (both are not allowed)
  # fromNodeAnnotationKey: "eks.amazonaws.com/nodegroup"

nodes:
  # kwok provider adds a taint on the template nodes
  # so that even if you run the provider in a production cluster
  # you don't have to worry about production workload
  # getting accidentally scheduled on the fake nodes
  # use skipTaint: true to disable this behavior (false by default)
  # skipTaint: false (default)
  gpuConfig:
    # to tell kwok provider what label should be considered as GPU label
    gpuLabelKey: "k8s.amazonaws.com/accelerator"
    availableGPUTypes:
      "nvidia-tesla-k80": {}
      "nvidia-tesla-p100": {}
