---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: recommender
        image: registry.k8s.io/autoscaling/vpa-recommender:1.2.2
        imagePullPolicy: IfNotPresent
        args:
          - /recommender
          - --ignored-vpa-object-namespaces=ignored-namespace
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: prometheus
          containerPort: 8942
---
apiVersion: v1
kind: Namespace
metadata:
  name: included-namespace
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: included-vpa
  namespace: included-namespace
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       included-app
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ignored-namespace
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ignored-vpa
  namespace: ignored-namespace
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       ignored-app
  updatePolicy:
    updateMode: "Auto"
