#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

# For the build step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.
# BINARY_PATH - path to an existing (empty) directory to place build results into.

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(${READLINK_BIN} -f $(dirname ${0})/..)"
else
  export SOURCE_PATH="$(${READLINK_BIN} -f "${SOURCE_PATH}")"
fi

if [[ -z "${BINARY_PATH}" ]]; then
  export BINARY_PATH="${SOURCE_PATH}"
else
  export BINARY_PATH="$(${READLINK_BIN} -f "${BINARY_PATH}")"
fi

###############################################################################

# Change to cluster-autoscaler directory that we can build with modules
cd ${SOURCE_PATH}/cluster-autoscaler
# ldflags used, same as Makefile , this reduces size of binary considerably
CGO_ENABLED=0 GO111MODULE=on go build --ldflags="-s -w" \
  -v \
  -o ${BINARY_PATH}/cluster-autoscaler/cluster-autoscaler \
  main.go
