{{- if not .Values.secretKeyRefNameOverride }}
{{- $isAzure := eq .Values.cloudProvider "azure" }}
{{- $isAws := eq .Values.cloudProvider "aws" }}
{{- $awsCredentialsProvided := and .Values.awsAccessKeyID .Values.awsSecretAccessKey }}
{{- $isCivo := eq .Values.cloudProvider "civo" }}

{{- if or $isAzure (and $isAws $awsCredentialsProvided) $isCivo }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- if $isAzure }}
  ClientID: "{{ .Values.azureClientID | b64enc }}"
  ClientSecret: "{{ .Values.azureClientSecret | b64enc }}"
  ResourceGroup: "{{ .Values.azureResourceGroup | b64enc }}"
  SubscriptionID: "{{ .Values.azureSubscriptionID | b64enc }}"
  TenantID: "{{ .Values.azureTenantID | b64enc }}"
  VMType: "{{ .Values.azureVMType | b64enc }}"
  UserAssignedIdentityID: "{{ .Values.azureUserAssignedIdentityID | b64enc }}"
{{- else if $isAws }}
  AwsAccessKeyId: "{{ .Values.awsAccessKeyID | b64enc }}"
  AwsSecretAccessKey: "{{ .Values.awsSecretAccessKey | b64enc }}"
{{- else if $isCivo }}
  api-url: "{{ .Values.civoApiUrl | b64enc }}"
  api-key: "{{ .Values.civoApiKey | b64enc }}"
  cluster-id: "{{ .Values.civoClusterID | b64enc }}"
  region: "{{ .Values.civoRegion | b64enc }}"
{{- end }}
{{- end }}
{{- end }}
