---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |-
    {
      "cluster_id": "<cluster-uuid>",
      "tenant_id": "<openstack-project-id>",
      "application_key": "<application-credential-id>",
      "application_secret": "<application-credential-secret>",
      "openstack_auth_url": "https://example.com:5000/v3"
    }
  vke-url: "https://vke-api.example.com"
