---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-autoscaling-x-k8s-io-v1alpha1-capacityquota
  failurePolicy: Fail
  name: vcapacityquota-v1alpha1.kb.io
  rules:
  - apiGroups:
    - autoscaling.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capacityquotas
  sideEffects: None
