# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3600s
options:
  # this prevents errors if you don't use both _GIT_TAG and _PULL_BASE_REF,
  # or any new substitutions added in the future.
  substitution_option: ALLOW_LOOSE
steps:
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:latest"
    entrypoint: make
    env:
      - TAG=$_GIT_TAG
    args:
      - execute-release
substitutions:
  _GIT_TAG: "0.0.0" # default value, this is substituted at build time
