apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-kamatera
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |-
    [global]
    kamatera-api-client-id=1a222bbb3ccc44d5555e6ff77g88hh9i
    kamatera-api-secret=9ii88h7g6f55555ee4444444dd33eee2
    cluster-name=aaabbb
    provider-id-prefix=kamatera://
    default-min-size=1
    default-max-size=10
    default-password=Aa123456789!
    default-ssh-key=ssh-rsa AAAAB3N....Rw==
    default-datacenter=IL
    default-image=ubuntu_server_18.04_64-bit
    default-cpu=1A
    default-ram=1024
    default-disk=size=50
    default-dailybackup=no
    default-managed=no
    default-network=name=wan,ip=auto
    default-billingcycle=hourly
    default-monthlypackage=
    default-script=<base64-encoded-initilaization-script>

    [nodegroup "default"]

    [nodegroup "highcpu"]
    cpu=2D

    [nodegroup "highram"]
    ram=4096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: registry.k8s.io/autoscaling/cluster-autoscaler:v{{ ca_version }}
          name: cluster-autoscaler
          command:
            - ./cluster-autoscaler
            - --cloud-provider=kamatera
            - --cloud-config=/config/cloud-config
            - --v=2
            - --logtostderr=true
            - --namespace=kube-system
          imagePullPolicy: "Always"
          volumeMounts:
            - name: cloud-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: cloud-config
          secret:
            secretName: cluster-autoscaler-kamatera
