FROM golang:1.6

ADD . /go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws-sdk-go

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws-sdk-go
CMD ["make", "get-deps", "unit-old-go-race-cover"]
