FROM golang:1.20.1

ADD . /go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws-sdk-go

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws-sdk-go
CMD ["make", "get-deps", "get-deps-x-tests", "get-deps-verify", "unit"]
