apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  labels:
    k8s-app: cluster-autoscaler
    version: {{VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cluster-autoscaler
      version: {{VERSION}}
  template:
    metadata:
      labels:
        k8s-app: cluster-autoscaler
        version: {{VERSION}}
    spec:
      containers:
        - image: {{REGISTRY}}/cluster-autoscaler:{{VERSION}}
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --nodes={{MIN}}:{{MAX}}:{{MIG_LINK}}
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
