version: "2"
linters:
  default: none
  enable:
    - forbidigo
  settings:
    forbidigo:
      forbid:
        # Forbid use of archived package "github.com/pkg/errors". Context: https://github.com/kubernetes/autoscaler/pull/7845
        - pkg: github.com/pkg/errors
      analyze-types: true
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - k8s.io/autoscaler/vertical-pod-autoscaler
