linters:
  enable:
    - forbidigo
    - goimports

linters-settings:
  forbidigo:
    forbid:
      # Forbid use of archived package "github.com/pkg/errors". Context: https://github.com/kubernetes/autoscaler/pull/7845
      - pkg: github.com/pkg/errors
    analyze-types: true

  goimports:
    local-prefixes: "k8s.io/autoscaler/vertical-pod-autoscaler"
