# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 7200s
# this prevents errors if you don't use both _GIT_TAG and _PULL_BASE_REF,
# or any new substitutions added in the future.
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:latest"
    dir: pkg/admission-controller
    entrypoint: make
    env:
      - TAG=$_GIT_TAG
    args:
      - release
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:latest"
    dir: pkg/recommender
    entrypoint: make
    env:
      - TAG=$_GIT_TAG
    args:
      - release
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:latest"
    dir: pkg/updater
    entrypoint: make
    env:
      - TAG=$_GIT_TAG
    args:
      - release
substitutions:
  _GIT_TAG: "0.0.0" # default value, this is substituted at build time
