version: "2"
run:
  go: "1.25"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - kubeapilinter # linter for Kube API conventions
  settings:
    custom:
      kubeapilinter:
        type: module
        description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              #- "commentstart" # Ensure comments start with the serialized version of the field name.
              #- "conditions" # Ensure conditions have the correct json tags and markers.
              #- "conflictingmarkers"
              #- "duplicatemarkers" # Ensure there are no exact duplicate markers. for types and fields.
              #- "integers" # Ensure only int32 and int64 are used for integers.
              #- "jsontags" # Ensure every field has a json tag.
              #- "maxlength" # Ensure all strings and arrays have maximum lengths/maximum items.
              - "nobools" # Bools do not evolve over time, should use enums instead.
              - "nodurations" # Prevents usage of `Duration` types.
              #- "nofloats" # Ensure floats are not used.
              #- "nomaps" # Ensure maps are not used.
              #- "nonullable" # Ensure that types and fields do not have the nullable marker.
              #- "optionalorrequired" # Every field should be marked as `+optional` or `+required`.
              #- "requiredfields" # Required fields should not be pointers, and should not have `omitempty`.
              #- "ssatags" # Ensure array fields have the appropriate listType markers
              #- "statusoptional" # Ensure all first children within status should be optional.
              #- "statussubresource" # All root objects that have a `status` field should have a status subresource.
              #- "uniquemarkers" # Ensure that types and fields do not contain more than a single definition of a marker that should only be present once.
            disable:
            - "*" # Disable all by default.
          lintersConfig:


  exclusions:
    build-tags:
      - ignore_autogenerated
    paths:
      - ".*_test.go"  # Exclude test files.
    rules:
    ## KAL should only run on APIS folders.
    - path-except: "apis//*"
      linters:
        - kubeapilinter

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
