name: Addon Resizer

on:
  push:
    paths:
      - 'addon-resizer/**'
      - '!addon-resizer/**/*.md'
      - '.github/workflows/addon-resizer.yaml'
  pull_request:
    paths:
      - 'addon-resizer/**'
      - '!addon-resizer/**/*.md'
      - '.github/workflows/addon-resizer.yaml'

permissions:
  contents: read

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'addon-resizer/go.mod'
          cache-dependency-path: 'addon-resizer/go.sum'

      - name: Build
        working-directory: addon-resizer
        run: go build ./...

      - name: Vet
        working-directory: addon-resizer
        run: go vet ./...

      - name: Test
        working-directory: addon-resizer
        run: go test ./...
