name: Cluster Autoscaler E2E (kwok)
on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read
  checks: write

jobs:
  e2e:
    name: CA E2E (kwok)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install Dependencies
        run: make install-dependencies

      - name: Test
        run: make run-e2e
