name: Cluster Autoscaler

on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.26'
          cache-dependency-path: go.sum

      - name: Apt-get
        run: sudo apt-get install libseccomp-dev -qq

      - name: Test
        run: make test-ci
        env:
          GO111MODULE: auto
          PROJECT_NAMES: ""