name: Verify Go

on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'hack/**'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'hack/**'

permissions:
  contents: read
  checks: write

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Apt-get
        run: sudo apt-get install libseccomp-dev -qq

      - name: Prepare
        run: hack/install-verify-tools.sh
        env:
          GO111MODULE: auto

      - name: Verify
        run: hack/verify-all.sh -v
        env:
          GO111MODULE: auto